version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta para comunicação AMQP
      - "15672:15672" # Porta para a interface de gerenciamento
      - "15692:15692" # Porta para métricas
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_WHOST=/
