POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
    "name": "My Product",
    "price": 100
}

###

GET http://localhost:8000/products/b845e332-d1ad-4351-859d-281be014ca66 HTTP/1.1

###

PUT http://localhost:8000/products/b845e332-d1ad-4351-859d-281be014ca66 HTTP/1.1
Content-Type: application/json

{
    "name": "My Product Updated",
    "price": 200
}

###

DELETE  http://localhost:8000/products/8337c992-080f-4125-b815-6abbcb83740f HTTP/1.1


###

GET  http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDE0NzYzODgsInN1YiI6IjlkZDk5MzY2LTI5YWItNDQ4NC04ZTI0LTc1NzlhYmNhYTM4ZSJ9.BK7d4vlxEUVrQJC-2khLRbmeibJxSEx-BzYsrH_dwqU